### ISSUE TITLE
[版本跟进专用] 官方最新稳定版跟踪

### ISSUE THREAD

**Issue by msojocs** [msojocs/wechat-web-devtools-linux#48]
此处用做版本更新提醒专用 issue 。

https://developers.weixin.qq.com/miniprogram/dev/devtools/stable.html

**Comment by sdlddr** [comment]
1.06.2206020
2022/6/3

**Comment by msojocs** [comment]
> 1.06.2206020 2022/6/3

get

**Comment by icepie** [comment]
> > 1.06.2206020 2022/6/3
> 
> get

aur 能抽空更新一下么

**Comment by sdlddr** [comment]
1.06.2206090

**Comment by smoothdvd** [comment]
稳定版 [Stable Build](https://developers.weixin.qq.com/miniprogram/dev/devtools/stable.html) (1.06.2207210)

**Comment by msojocs** [comment]
> 稳定版 [Stable Build](https://developers.weixin.qq.com/miniprogram/dev/devtools/stable.html) (1.06.2207210)

编译器位置移动，得花点时间。

**Comment by icepie** [comment]
稳定版 [Stable Build](https://developers.weixin.qq.com/miniprogram/dev/devtools/stable.html) (1.06.2208010)

自己打包了一下, 发现编译器还有点问题

**Comment by msojocs** [comment]
> 稳定版 [Stable Build](https://developers.weixin.qq.com/miniprogram/dev/devtools/stable.html) (1.06.2208010)
> 
> 自己打包了一下, 发现编译器还有点问题

并没有发布release，因为编译器还没有跟进。

**Comment by icepie** [comment]
> > 稳定版 [Stable Build](https://developers.weixin.qq.com/miniprogram/dev/devtools/stable.html) (1.06.2208010)
> > 自己打包了一下, 发现编译器还有点问题
> 
> 并没有发布release，因为编译器还没有跟进。

本来以为自己可以修一下的, 有点高估了自己...还是等你有空处理一下吧! 感谢!

**Comment by jcleng** [comment]
flatpak格式的包在哪里下载哦,没看到

**Comment by msojocs** [comment]
> flatpak格式的包在哪里下载哦,没看到

不知道，flatpak有包吗？

**Comment by jcleng** [comment]
> 

我看你构建的update: flatpak https://github.com/msojocs/wechat-web-devtools-linux/actions/runs/2724126335

这个是flatpak的包吗,我参考`io.github.msojocs.wechat-devtools.yml`这个文件直接用`WeChat_Dev_Tools_v1.06.2206090-2_x86_64_no_wine`的包可以构建出来. 但是同样会提示这个: , 估计还是编译器不太兼容
```
[ WXML 文件编译错误] 
环境及执行信息：
编译器版本: 20220511
node版本: v16.4.2
参数: --config-path /tmp/46b3a90f5511f0f77576a793ac4863a3

具体报错：
Error -1152: WXML file not found: 
```

构建flatpak

```yml
app-id: org.jcleng.wechat_web_devtools_linux
runtime: org.freedesktop.Platform
runtime-version: '21.08'
sdk: org.freedesktop.Sdk
sdk-extensions:
  - org.freedesktop.Sdk.Extension.node12
command: /app/bin/wechat-devtools/bin/wechat-devtools
finish-args:
  # X11 + XShm access
  - --share=ipc
  - --socket=x11
  # Wayland access
  - --socket=wayland
  # Needs to talk to the network:
  - --share=network
  # Needs to save files locally
  - --filesystem=host
modules:
  - name: wechat-devtools
    buildsystem: simple
    build-commands:
      - mkdir -p /app/bin/wechat-devtools
      - cp -r ./* /app/bin/wechat-devtools
      - ls /app/bin/
    sources:
      - type: dir
        path: WeChat_Dev_Tools_v1.06.2206090-2_x86_64_no_wine

```
